spring:
  config:
    import:
     - classpath:db.properties
  cloud:
    compatibility-verifier:
      enabled: false
  profiles:
    group:
      default: h2

logging:
  level:
    org.springframework.transaction.interceptor: TRACE

client:
  kakao:
    url: https://dapi.kakao.com
    app-key: KakaoAK cfb90d2eb84ca8aa1e74e124d10d8e1f
  naver:
    url: https://openapi.naver.com
    client-id: GM4H0FZdsJS9UiRPTEPq
    secret: dDui8jzvQH
